module: site
portal: wal.app
package: 0x26eb7ee8688da02c5f671679524e379f0b837a12f1d1d799f255b7eea260ad27
general:
  wallet_env: mainnet
  walrus_context: mainnet # Assumes a Walrus CLI setup with a multi-config containing the "mainnet" context.

